[package]
name = "phobos-cluster"
version = "0.1.0"
edition.workspace = true
description = "Cluster IR, node ISA, and the cluster compiler for Phobos"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["compilers", "development-tools"]

[dependencies]
anyhow = "1"
phobos-base = { path = "../phobos-base" }
phobos-lang = { path = "../phobos-lang" }
tonic.workspace = true
prost.workspace = true

[build-dependencies]
tonic-build.workspace = true
protoc-bin-vendored = "3"

[dev-dependencies]
melior.workspace = true
